In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('DMart_sample_data.csv')
df.head()

,Date,Time,CustomerType,ProductCategory,UnitPrice,Quantity,Total,FullName
0,31-12-2023 15:41,06:04:28,Member,Grocery,10.69,4,42.76,Jai Bhatia
1,07-01-2024 22:19,01:05:18,Premium,Home & Kitchen,381.03,3,1143.09,Ishaan Patel
2,10-01-2024 02:09,17:31:43,Regular,Grocery,153.84,5,769.20,Tanvi Iyer
3,01-06-2023 10:46,01:50:16,Regular,Electronics,341.41,4,1365.64,Zara Xavier
4,23-05-2024 22:07,10:37:06,Regular,Home & Kitchen,390.16,5,1950.80,Krishna Zutshi

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 8 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   Date             1000000 non-null  object
 1   Time             1000000 non-null  object
 2   CustomerType     1000000 non-null  object
 3   ProductCategory  1000000 non-null  object
 4   UnitPrice        1000000 non-null  float64
 5   Quantity         1000000 non-null  int64
 6   Total            1000000 non-null  float64
 7   FullName         1000000 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 61.0+ MB

In [3]:
df.describe()
df.describe(include='all')

,Date,Time,CustomerType,ProductCategory,UnitPrice,Quantity,Total,FullName
count,1000000,1000000,1000000,1000000,1000000.000000,1000000.000000,1000000.000000,1000000
unique,648427,86400,3,5,NaN,NaN,NaN,400
top,08-03-2024 11:46,02:26:35,Premium,Home & Kitchen,NaN,NaN,NaN,Eeshaan Bhatia
freq,8,28,333480,200424,NaN,NaN,NaN,2641
mean,NaN,NaN,NaN,NaN,255.134171,2.999324,765.094619,NaN
std,NaN,NaN,NaN,NaN,141.442440,1.413537,591.113890,NaN
min,NaN,NaN,NaN,NaN,10.000000,1.000000,10.000000,NaN
25%,NaN,NaN,NaN,NaN,132.660000,2.000000,290.640000,NaN
50%,NaN,NaN,NaN,NaN,255.140000,3.000000,604.700000,NaN
75%,NaN,NaN,NaN,NaN,377.510000,4.000000,1133.160000,NaN
max,NaN,NaN,NaN,NaN,500.000000,5.000000,2500.000000,NaN

In [4]:
df.isnull().sum()

Date               0
Time               0
CustomerType       0
ProductCategory    0
UnitPrice          0
Quantity           0
Total              0
FullName           0
dtype: int64

In [6]:
df.columns = df.columns.str.strip().str.upper()  # removes spaces, lowercases everything
df.columns

Index(['DATE', 'TIME', 'CUSTOMERTYPE', 'PRODUCTCATEGORY', 'UNITPRICE',
       'QUANTITY', 'TOTAL', 'FULLNAME'],
      dtype='object')

In [13]:
df = df.drop_duplicates()
df = df.fillna(0)
df['DATE'] = pd.to_datetime(df['DATE'], dayfirst=True)   # Fix date dtype
df['TIME'] = pd.to_datetime(df['TIME'], format='%H:%M:%S').dt.time
df.columns = df.columns.str.strip().str.upper()           # Already done ✅
df.head(20)

,DATE,TIME,CUSTOMERTYPE,PRODUCTCATEGORY,UNITPRICE,QUANTITY,TOTAL,FULLNAME
0,2023-12-31 15:41:00,06:04:28,Member,Grocery,10.69,4,42.76,Jai Bhatia
1,2024-01-07 22:19:00,01:05:18,Premium,Home & Kitchen,381.03,3,1143.09,Ishaan Patel
2,2024-01-10 02:09:00,17:31:43,Regular,Grocery,153.84,5,769.20,Tanvi Iyer
3,2023-06-01 10:46:00,01:50:16,Regular,Electronics,341.41,4,1365.64,Zara Xavier
4,2024-05-23 22:07:00,10:37:06,Regular,Home & Kitchen,390.16,5,1950.80,Krishna Zutshi
5,2024-02-16 19:41:00,22:41:47,Member,Grocery,170.21,4,680.84,Zara Singh
6,2023-11-30 03:36:00,09:36:45,Member,Clothing,81.74,2,163.48,Eeshaan Xavier
7,2024-06-05 05:21:00,20:02:39,Premium,Clothing,181.26,3,543.78,Eeshaan Kumar
8,2024-06-07 21:40:00,21:07:44,Premium,Electronics,471.89,2,943.78,Mahesh Mehta
9,2023-12-29 04:35:00,17:53:54,Member,Grocery,59.70,2,119.40,Ishaan Verma
10,2024-12-13 15:25:00,21:08:19,Regular,Electronics,198.48,4,793.92,Krishna Agarwal
11,2023-03-30 21:54:00,00:21:31,Member,Grocery,242.14,2,484.28,Vaibhav Singh
12,2023-06-02 14:06:00,18:22:19,Premium,Beauty & Personal Care,45.87,3,137.61,Shreya Khanna
13,2023-10-27 11:33:00,11:26:47,Premium,Home & Kitchen,120.57,5,602.85,Rohan Mehta
14,2024-12-07 13:54:00,01:24:43,Member,Beauty & Personal Care,189.30,1,189.30,Nandini Wadhwa
15,2023-12-30 06:34:00,20:28:06,Regular,Electronics,104.18,3,312.54,Bhavesh Verma
16,2023-07-23 01:20:00,13:37:30,Member,Grocery,294.16,3,882.48,Zara Mehta
17,2023-12-11 17:08:00,05:36:15,Premium,Home & Kitchen,299.65,5,1498.25,Diya Wadhwa
18,2024-11-13 10:46:00,06:33:07,Regular,Grocery,467.27,4,1869.08,Vaibhav Xavier
19,2024-09-03 01:02:00,09:43:42,Regular,Grocery,142.98,2,285.96,Mahesh Zutshi

In [15]:
df['MONTH'] = df['DATE'].dt.month_name()
df['YEAR'] = df['DATE'].dt.year
df['DAY_OF_WEEK'] = df['DATE'].dt.day_name()
df['HOUR'] = pd.to_datetime(df['TIME'], format='%H:%M:%S').dt.hour
df['REVENUE_PER_UNIT'] = df['TOTAL'] / df['QUANTITY']
df.head()

,DATE,TIME,CUSTOMERTYPE,PRODUCTCATEGORY,UNITPRICE,QUANTITY,TOTAL,FULLNAME,MONTH,YEAR,DAY_OF_WEEK,HOUR,REVENUE_PER_UNIT
0,2023-12-31 15:41:00,06:04:28,Member,Grocery,10.69,4,42.76,Jai Bhatia,December,2023,Sunday,6,10.69
1,2024-01-07 22:19:00,01:05:18,Premium,Home & Kitchen,381.03,3,1143.09,Ishaan Patel,January,2024,Sunday,1,381.03
2,2024-01-10 02:09:00,17:31:43,Regular,Grocery,153.84,5,769.20,Tanvi Iyer,January,2024,Wednesday,17,153.84
3,2023-06-01 10:46:00,01:50:16,Regular,Electronics,341.41,4,1365.64,Zara Xavier,June,2023,Thursday,1,341.41
4,2024-05-23 22:07:00,10:37:06,Regular,Home & Kitchen,390.16,5,1950.80,Krishna Zutshi,May,2024,Thursday,10,390.16

In [22]:
# Same as above but cleaner syntax
df.query("CUSTOMERTYPE == 'Premium'")
df.query("TOTAL > 1000")
df.query("CUSTOMERTYPE == 'Premium' and TOTAL > 1000")
df.query("PRODUCTCATEGORY == 'Grocery' or PRODUCTCATEGORY == 'Electronics'")

# Using 'in' for multiple values
#df.query("PRODUCTCATEGORY in ['Grocery', 'Electronics']")

,DATE,TIME,CUSTOMERTYPE,PRODUCTCATEGORY,UNITPRICE,QUANTITY,TOTAL,FULLNAME,MONTH,YEAR,DAY_OF_WEEK,HOUR,REVENUE_PER_UNIT
0,2023-12-31 15:41:00,06:04:28,Member,Grocery,10.69,4,42.76,Jai Bhatia,December,2023,Sunday,6,10.69
2,2024-01-10 02:09:00,17:31:43,Regular,Grocery,153.84,5,769.20,Tanvi Iyer,January,2024,Wednesday,17,153.84
3,2023-06-01 10:46:00,01:50:16,Regular,Electronics,341.41,4,1365.64,Zara Xavier,June,2023,Thursday,1,341.41
5,2024-02-16 19:41:00,22:41:47,Member,Grocery,170.21,4,680.84,Zara Singh,February,2024,Friday,22,170.21
8,2024-06-07 21:40:00,21:07:44,Premium,Electronics,471.89,2,943.78,Mahesh Mehta,June,2024,Friday,21,471.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999991,2023-07-09 22:54:00,00:31:20,Premium,Electronics,362.29,5,1811.45,Uday Chauhan,July,2023,Sunday,0,362.29
999993,2023-09-18 16:06:00,00:00:41,Regular,Electronics,180.66,3,541.98,Uday Wadhwa,September,2023,Monday,0,180.66
999994,2023-03-28 20:18:00,11:39:45,Premium,Grocery,343.25,2,686.50,Zara Chauhan,March,2023,Tuesday,11,343.25
999995,2023-08-16 21:13:00,15:37:01,Premium,Electronics,256.80,1,256.80,Priya Wadhwa,August,2023,Wednesday,15,256.80
999996,2024-01-18 13:01:00,15:05:47,Regular,Electronics,191.20,3,573.60,Nandini Iyer,January,2024,Thursday,15,191.20

In [35]:
df.query("YEAR =='2023'")
df.query("MONTH == 'August' ") 
df.query("CUSTOMERTYPE == 'Regular' ")

,DATE,TIME,CUSTOMERTYPE,PRODUCTCATEGORY,UNITPRICE,QUANTITY,TOTAL,FULLNAME,MONTH,YEAR,DAY_OF_WEEK,HOUR,REVENUE_PER_UNIT
2,2024-01-10 02:09:00,17:31:43,Regular,Grocery,153.84,5,769.20,Tanvi Iyer,January,2024,Wednesday,17,153.84
3,2023-06-01 10:46:00,01:50:16,Regular,Electronics,341.41,4,1365.64,Zara Xavier,June,2023,Thursday,1,341.41
4,2024-05-23 22:07:00,10:37:06,Regular,Home & Kitchen,390.16,5,1950.80,Krishna Zutshi,May,2024,Thursday,10,390.16
10,2024-12-13 15:25:00,21:08:19,Regular,Electronics,198.48,4,793.92,Krishna Agarwal,December,2024,Friday,21,198.48
15,2023-12-30 06:34:00,20:28:06,Regular,Electronics,104.18,3,312.54,Bhavesh Verma,December,2023,Saturday,20,104.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999988,2024-06-12 05:39:00,13:27:17,Regular,Beauty & Personal Care,14.15,4,56.60,Zara Lal,June,2024,Wednesday,13,14.15
999992,2024-01-27 08:22:00,21:15:07,Regular,Home & Kitchen,283.34,3,850.02,Vaibhav Yadav,January,2024,Saturday,21,283.34
999993,2023-09-18 16:06:00,00:00:41,Regular,Electronics,180.66,3,541.98,Uday Wadhwa,September,2023,Monday,0,180.66
999996,2024-01-18 13:01:00,15:05:47,Regular,Electronics,191.20,3,573.60,Nandini Iyer,January,2024,Thursday,15,191.20
999998,2024-04-03 14:55:00,10:14:32,Regular,Home & Kitchen,39.27,3,117.81,Nandini Wadhwa,April,2024,Wednesday,10,39.27

In [ ]:
df[(df['TOTAL'] >= 500) & (df['TOTAL'] <= 1000)]  # compare prices

,DATE,TIME,CUSTOMERTYPE,PRODUCTCATEGORY,UNITPRICE,QUANTITY,TOTAL,FULLNAME,MONTH,YEAR,DAY_OF_WEEK,HOUR,REVENUE_PER_UNIT
2,2024-01-10 02:09:00,17:31:43,Regular,Grocery,153.84,5,769.20,Tanvi Iyer,January,2024,Wednesday,17,153.84
5,2024-02-16 19:41:00,22:41:47,Member,Grocery,170.21,4,680.84,Zara Singh,February,2024,Friday,22,170.21
7,2024-06-05 05:21:00,20:02:39,Premium,Clothing,181.26,3,543.78,Eeshaan Kumar,June,2024,Wednesday,20,181.26
8,2024-06-07 21:40:00,21:07:44,Premium,Electronics,471.89,2,943.78,Mahesh Mehta,June,2024,Friday,21,471.89
10,2024-12-13 15:25:00,21:08:19,Regular,Electronics,198.48,4,793.92,Krishna Agarwal,December,2024,Friday,21,198.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999985,2023-08-23 07:18:00,18:30:06,Premium,Electronics,162.17,4,648.68,Krishna Lal,August,2023,Wednesday,18,162.17
999992,2024-01-27 08:22:00,21:15:07,Regular,Home & Kitchen,283.34,3,850.02,Vaibhav Yadav,January,2024,Saturday,21,283.34
999993,2023-09-18 16:06:00,00:00:41,Regular,Electronics,180.66,3,541.98,Uday Wadhwa,September,2023,Monday,0,180.66
999994,2023-03-28 20:18:00,11:39:45,Premium,Grocery,343.25,2,686.50,Zara Chauhan,March,2023,Tuesday,11,343.25
999996,2024-01-18 13:01:00,15:05:47,Regular,Electronics,191.20,3,573.60,Nandini Iyer,January,2024,Thursday,15,191.20

In [ ]:
df[df['FULLNAME'] == 'Jai Bhatia']   # purchase made by specific customer

,DATE,TIME,CUSTOMERTYPE,PRODUCTCATEGORY,UNITPRICE,QUANTITY,TOTAL,FULLNAME,MONTH,YEAR,DAY_OF_WEEK,HOUR,REVENUE_PER_UNIT
0,2023-12-31 15:41:00,06:04:28,Member,Grocery,10.69,4,42.76,Jai Bhatia,December,2023,Sunday,6,10.69
323,2025-01-01 21:57:00,15:18:45,Regular,Home & Kitchen,171.23,4,684.92,Jai Bhatia,January,2025,Wednesday,15,171.23
397,2024-04-23 16:43:00,02:21:36,Premium,Clothing,498.72,5,2493.60,Jai Bhatia,April,2024,Tuesday,2,498.72
1357,2024-08-24 11:08:00,12:55:41,Premium,Beauty & Personal Care,173.04,2,346.08,Jai Bhatia,August,2024,Saturday,12,173.04
1542,2023-01-22 15:45:00,02:11:56,Member,Home & Kitchen,439.13,3,1317.39,Jai Bhatia,January,2023,Sunday,2,439.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
998884,2024-10-28 22:36:00,12:38:15,Premium,Home & Kitchen,316.38,3,949.14,Jai Bhatia,October,2024,Monday,12,316.38
999053,2023-01-09 16:58:00,04:05:39,Premium,Beauty & Personal Care,249.60,4,998.40,Jai Bhatia,January,2023,Monday,4,249.60
999453,2024-06-19 01:49:00,02:05:00,Regular,Grocery,481.25,1,481.25,Jai Bhatia,June,2024,Wednesday,2,481.25
999717,2023-12-05 11:09:00,19:39:17,Regular,Home & Kitchen,60.99,1,60.99,Jai Bhatia,December,2023,Tuesday,19,60.99
999821,2024-10-19 01:24:00,20:43:43,Regular,Beauty & Personal Care,127.96,1,127.96,Jai Bhatia,October,2024,Saturday,20,127.96

In [ ]:
# NOT a Regular customer (~ means NOT)
df[~(df['CUSTOMERTYPE'] == 'Regular')]

,DATE,TIME,CUSTOMERTYPE,PRODUCTCATEGORY,UNITPRICE,QUANTITY,TOTAL,FULLNAME,MONTH,YEAR,DAY_OF_WEEK,HOUR,REVENUE_PER_UNIT
0,2023-12-31 15:41:00,06:04:28,Member,Grocery,10.69,4,42.76,Jai Bhatia,December,2023,Sunday,6,10.69
1,2024-01-07 22:19:00,01:05:18,Premium,Home & Kitchen,381.03,3,1143.09,Ishaan Patel,January,2024,Sunday,1,381.03
5,2024-02-16 19:41:00,22:41:47,Member,Grocery,170.21,4,680.84,Zara Singh,February,2024,Friday,22,170.21
6,2023-11-30 03:36:00,09:36:45,Member,Clothing,81.74,2,163.48,Eeshaan Xavier,November,2023,Thursday,9,81.74
7,2024-06-05 05:21:00,20:02:39,Premium,Clothing,181.26,3,543.78,Eeshaan Kumar,June,2024,Wednesday,20,181.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999991,2023-07-09 22:54:00,00:31:20,Premium,Electronics,362.29,5,1811.45,Uday Chauhan,July,2023,Sunday,0,362.29
999994,2023-03-28 20:18:00,11:39:45,Premium,Grocery,343.25,2,686.50,Zara Chauhan,March,2023,Tuesday,11,343.25
999995,2023-08-16 21:13:00,15:37:01,Premium,Electronics,256.80,1,256.80,Priya Wadhwa,August,2023,Wednesday,15,256.80
999997,2023-10-05 19:16:00,05:38:49,Premium,Home & Kitchen,324.33,5,1621.65,Zara Jain,October,2023,Thursday,5,324.33
999999,2024-01-22 22:44:00,03:58:37,Member,Home & Kitchen,347.68,4,1390.72,Priya Gupta,January,2024,Monday,3,347.68

In [42]:
#  Top 5 highest transactions
df.nlargest(5, 'TOTAL')

#  Bottom 5 lowest transactions
df.nsmallest(5, 'TOTAL')

,DATE,TIME,CUSTOMERTYPE,PRODUCTCATEGORY,UNITPRICE,QUANTITY,TOTAL,FULLNAME,MONTH,YEAR,DAY_OF_WEEK,HOUR,REVENUE_PER_UNIT
43429,2023-10-30 04:16:00,20:07:30,Premium,Home & Kitchen,10.00,1,10.00,Bhavesh Singh,October,2023,Monday,20,10.00
848901,2024-12-25 10:20:00,01:57:41,Regular,Home & Kitchen,10.00,1,10.00,Uday Gupta,December,2024,Wednesday,1,10.00
922232,2023-11-09 14:11:00,11:11:58,Premium,Clothing,10.00,1,10.00,Mahesh Xavier,November,2023,Thursday,11,10.00
737055,2023-02-19 02:05:00,03:36:19,Member,Clothing,10.01,1,10.01,Eeshaan Khanna,February,2023,Sunday,3,10.01
22187,2024-03-19 06:18:00,00:28:27,Member,Grocery,10.02,1,10.02,Priya Bhatia,March,2024,Tuesday,0,10.02

In [43]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in C:\python11\Lib\site-packages (1.1.3)
Requirement already satisfied: sqlalchemy in C:\python11\Lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in C:\python11\Lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\python11\Lib\site-packages (from sqlalchemy) (4.14.1)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
from sqlalchemy import create_engine, text

username="root"
password="shravan123"
host="localhost"
port=3306
database="dmart_sales"

# Connect to MySQL server and create the database if it does not exist
engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/')
with engine.connect() as conn:
    conn.execute(text(f"CREATE DATABASE IF NOT EXISTS `{database}`"))
    conn.commit()
engine.dispose()

# Reconnect using the created database
engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

table_name = "dmart_sales"
df.to_sql(table_name, con=engine, if_exists='replace', index=False)

pd.read_sql('SELECT * FROM dmart_sales LIMIT 5', con=engine)

,DATE,TIME,CUSTOMERTYPE,PRODUCTCATEGORY,UNITPRICE,QUANTITY,TOTAL,FULLNAME,MONTH,YEAR,DAY_OF_WEEK,HOUR,REVENUE_PER_UNIT
0,2023-12-31 15:41:00,0 days 06:04:28,Member,Grocery,10.69,4,42.76,Jai Bhatia,December,2023,Sunday,6,10.69
1,2024-01-07 22:19:00,0 days 01:05:18,Premium,Home & Kitchen,381.03,3,1143.09,Ishaan Patel,January,2024,Sunday,1,381.03
2,2024-01-10 02:09:00,0 days 17:31:43,Regular,Grocery,153.84,5,769.20,Tanvi Iyer,January,2024,Wednesday,17,153.84
3,2023-06-01 10:46:00,0 days 01:50:16,Regular,Electronics,341.41,4,1365.64,Zara Xavier,June,2023,Thursday,1,341.41
4,2024-05-23 22:07:00,0 days 10:37:06,Regular,Home & Kitchen,390.16,5,1950.80,Krishna Zutshi,May,2024,Thursday,10,390.16